# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestGraph' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Swinject'
  pod 'SwinjectStoryboard'
  
  pod 'RxSwift'
  pod 'Charts'
  pod 'SnapKit'

  # Pods for TestGraph

end

target 'TestGraphTests' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    pod 'Charts'
    
    # Pods for TestGraphTests
    
end
